### ISSUE TITLE
newbie problem?

### ISSUE THREAD

**Issue by brian-reed** [nunit/nunit.xamarin#23]
Not sure proper way to ask this, is there a separate forum instead of submitting an issue?  I am fairly new to Xamarin - have just written test apps and taken several classes.  I am brand new to using nunit. I followed the instructions to clone the project and build it using VS2015.  I got a clean build, but upon trying to run the tests in the nunit.runner.tests.Droid project in the cloned solution I only got the following in the output window for Tests:

------ Discover test started ------
========== Discover test finished: 0 found (0:00:00.0557507) ==========

I can see that there are several tests in TestSample.cs and TestCaseSample.cs, but above shows no tests discovered and so nothing is run.
The references in the nunit.runner.tests.Droid project show the version for nunit.framework is 3.0.5715.30859 and for nunit.runner.droid is 3.0.5744.22087

Not sure if the is an issue or just a setup problem, but I'm unable to determine why the tests aren't being detected.

**Comment by rprouse** [comment]
Because the tests are compiled for Android, they cannot run on your Windows machine. That is why the nunit test adapter in Visual Studio does not detect the tests. To run the tests, set the test project as a startup project and run it. It should deploy to an emulator or a physical device and run the tests in a GUI there.

Hopefully within the week we will have NuGet packages uploaded so that you can use this in your own project.

I am going to close this as a question, but feel free to continue to comment on the issue. I will see all of your responses if you have additional questions.

**Comment by CharliePoole** [comment]
Also, a good place for questions is our nunit-discuss group on Google groups.

**Comment by brian-reed** [comment]
Thanks CharliePoole, good to know about the Google group.  And thanks rprouse for the info.  I incorrectly assumed that running tests from the Test menu in VS would launch onto the device.  I really like how the device displays the test results.

An additional question if you don't mind - Does the app that runs on the device also generate a test results xml file on the device that could be uploaded from the device?

**Comment by rprouse** [comment]
It doesn't create a result file, but that is a really good idea. Could you create an issue for that? 

Eventually, I want to add a network channel that allows you to control tests from your desktop and view results, but that is probably a long way out. 

I'm glad you like the UI, I spent a few nights tweaking it. Ideas for improvements are welcome, I'm a developer not a designer :)
